# Generated by Django 3.0.3 on 2021-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='putdata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='putdata',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='putdata',
            name='room',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='putdata',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='putdata',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
